export const ALLOWED_IMAGES = new Set(["python", "debian", "alpine"]);
export const PREFIX = "sbx-";
export const SESSION_COOKIE = "session_id";
export const MAX_CONCURRENT = 3;
export const NAME_RE = /^[a-z0-9][a-z0-9-]{1,30}$/;
export const MAX_SANDBOXES = 5;
export const EXEC_TIMEOUT_MS = 30_000;
export const TIMEOUT_MS = 30_000;
export const SESSION_TTL_SECONDS = 60 * 60;
export const DEFAULT_CPUS = 1; // 1 vcpu
export const DEFAULT_MEMORY = 512; //512 mb
